### ISSUE TITLE
ARM bl instruction with supplied label fails to assemble

### ISSUE THREAD

**Issue by adrianherrera** [emproof-com/nyxstone#63]
Branch and link to a provided label fails to assemble.

E.g.,:

```python
from nyxstone import Nyxstone

ns = Nyxstone("arm")
ns.assemble("bl .label", labels={".label": 0x1000})
```

Produces the error:

```
ValueError: Error during assembly: error: Could not resolve relocation/label (reported by Nyxstone)
bl .label
^
```

Note that `ns.assemble("b .label", labels={".label": 0x1000})` works.

**Comment by stuxnot** [comment]
Thank you for reporting this. LLVM seems to emit a relocation for `bl` but not for `b`, but only if the triple/architecture is specified as a shorthand. If you use `thumbv8`, `aarch64`, or `armv8m.main-none-eabi` as the triple, Nyxstone is able to assemble the `bl`. We will update the README and docs to make selecting triples easier.

**Comment by adrianherrera** [comment]
Oooooh, okay! Thanks for the quick response + updates!
